(() => {
  const root=document.querySelector('[data-game]'),$=s=>root.querySelector(s),audio=$('[data-song]');
  const intro=document.querySelector('[data-intro]'),success=document.querySelector('[data-success]');
  const riff=[1,0,1,1,0,1,0,1,1,0,1],rounds=[{start:0,call:6},{start:4,call:6},{start:8,call:6}],stepMs=205;
  let state,songTimer;
  const seq=(start,count)=>Array.from({length:count},(_,i)=>riff[(start+i)%11]);
  function reset(){clearTimeout(songTimer);audio.pause();audio.currentTime=0;state={round:-1,response:[0,0,0,0,0],busy:false,pulseView:false};$('[data-log]').innerHTML='';$('[data-contact-title]').textContent='CONTACT PENDING';$('[data-round]').textContent='—';$('[data-ring-status]').textContent='AWAITING CARRIER';$('[data-instruction]').textContent='Listen before deciding what the signal is.';$('[data-call-state]').textContent='NO DATA';$('[data-call-state]').classList.remove('live');$('.signal-strength').classList.remove('receiving');$('[data-ring]').classList.remove('visible');$('[data-satellite]').classList.remove('active');$('[data-memory-note]').hidden=true;$('[data-loop-opening]').classList.remove('active');$('[data-pulse-view]').classList.remove('active');buildRing();renderCall([]);renderResponse();enable(false);updatePlay()}
  function buildRing(){$('[data-ring]').innerHTML=riff.map((v,i)=>`<span class="ring-step" data-ring-step="${i}" style="--a:${i*360/11}deg">${String(i+1).padStart(2,'0')}</span>`).join('')}
  function renderCall(values){$('[data-call-steps]').innerHTML=values.map((v,i)=>`<i class="mini-step ${v?'on':''}" data-call-step="${i}"></i>`).join('')}
  function renderResponse(){$('[data-response-steps]').innerHTML=state.response.map((v,i)=>`<button class="response-step ${v?'on':''}" data-response="${i}" aria-label="Response step ${i+1}, ${v?'on':'off'}">${i+1}</button>`).join('');document.querySelectorAll('[data-response]').forEach(b=>b.addEventListener('click',()=>{if(state.busy)return;const i=+b.dataset.response;state.response[i]^=1;renderResponse()}))}
  function enable(on){$('[data-play-call]').disabled=!on;$('[data-clear]').disabled=!on;$('[data-transmit]').disabled=!on}
  function beep(on,time=0,kind='call'){if(!on)return;const C=window.AudioContext||window.webkitAudioContext;state.ctx||=new C();const o=state.ctx.createOscillator(),g=state.ctx.createGain(),at=state.ctx.currentTime+time;o.type=kind==='call'?'sine':'triangle';o.frequency.value=kind==='call'?520:330;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.07,at+.015);g.gain.exponentialRampToValueAtTime(.0001,at+.13);o.connect(g).connect(state.ctx.destination);o.start(at);o.stop(at+.15)}
  function play(values,kind='call'){if(state.busy)return Promise.resolve();state.busy=true;const nodes=kind==='call'?document.querySelectorAll('[data-call-step]'):document.querySelectorAll('[data-response]');values.forEach((v,i)=>{beep(v,i*stepMs/1000,kind);setTimeout(()=>nodes[i]?.classList.add('playing'),i*stepMs);setTimeout(()=>nodes[i]?.classList.remove('playing'),i*stepMs+150)});return new Promise(r=>setTimeout(()=>{state.busy=false;r()},values.length*stepMs+100))}
  function log(tag,text){const li=document.createElement('li');li.innerHTML=`<b>${tag}</b>${text}`;$('[data-log]').prepend(li);while($('[data-log]').children.length>5)$('[data-log]').lastChild.remove()}
  async function begin(){intro.close();audio.currentTime=5.8;await audio.play().catch(()=>{});updatePlay();log('ARCHIVE','Personal media playback started.');$('[data-contact-title]').textContent='PASSIVE LISTENING';songTimer=setTimeout(interrupt,6500)}
  function interrupt(){audio.pause();updatePlay();$('.signal-strength').classList.add('receiving');$('[data-satellite]').classList.add('active');$('[data-contact-title]').textContent='CARRIER INTERRUPT';$('[data-memory-note]').hidden=false;log('CARRIER','Unregistered timing exchange interrupted local audio.');$('[data-instruction]').textContent='The carrier repeats on an eleven-step cycle. It may be waiting for the rest.';setTimeout(()=>startRound(0),700)}
  function startRound(n){state.round=n;state.response=[0,0,0,0,0];const r=rounds[n],call=seq(r.start,r.call);renderCall(call);renderResponse();enable(true);$('[data-ring]').classList.add('visible');$('[data-round]').textContent=`0${n+1}`;$('[data-ring-status]').textContent=`HANDSHAKE ${n+1} / 3`;$('[data-call-state]').textContent='REPEATING';$('[data-call-state]').classList.add('live');document.querySelectorAll('[data-ring-step]').forEach((el,i)=>el.classList.toggle('on',riff[i]&&state.pulseView));log(`ROUND ${n+1}`,'Carrier issued a partial cycle.');play(call)}
  async function transmit(){if(state.busy)return;enable(false);await play(state.response,'response');const r=rounds[state.round],want=seq(r.start+r.call,5),ok=state.response.every((v,i)=>v===want[i]);if(!ok){log('NO LOCK','Response broke continuity. Carrier restarted the round.');$('[data-instruction]').textContent='The signal did not continue through your response. Compare where the received phrase stopped.';state.response=[0,0,0,0,0];renderResponse();enable(true);setTimeout(()=>play(seq(r.start,r.call)),450);return}log('PHASE LOCK',`Continuation ${state.round+1} accepted.`);flash(r.start);if(state.round<2){$('[data-instruction]').textContent='It answered—but began the same cycle somewhere else.';setTimeout(()=>startRound(state.round+1),1300)}else setTimeout(complete,1400)}
  function flash(start){document.querySelectorAll('[data-ring-step]').forEach((el,i)=>{const d=((i-start+11)%11)*stepMs;setTimeout(()=>el.classList.add('playing'),d);setTimeout(()=>el.classList.remove('playing'),d+170)})}
  function complete(){enable(false);$('[data-contact-title]').textContent='RELAY 11 RESOLVED';$('[data-ring-status]').textContent='UNREGISTERED PARTICIPANT';$('[data-round]').textContent='11';log('CONTACT','A hidden relay joined the Bellweather network.');$('[data-observation] p').textContent='Registered relays nominal. An eleventh participant now shares their clock.';setTimeout(()=>success.showModal(),700)}
  const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`,updatePlay=()=>$('[data-song-play]').textContent=audio.paused?'▶':'Ⅱ';
  audio.addEventListener('timeupdate',()=>{const p=audio.currentTime/(audio.duration||171.57)*100;$('[data-progress]').style.width=`${p}%`;$('[data-scrub]').value=audio.currentTime;$('[data-song-time]').textContent=fmt(audio.currentTime);if($('[data-loop-opening]').classList.contains('active')&&audio.currentTime>15.1)audio.currentTime=5.8});audio.addEventListener('play',updatePlay);audio.addEventListener('pause',updatePlay);
  $('[data-song-play]').addEventListener('click',()=>audio.paused?audio.play():audio.pause());$('[data-scrub]').addEventListener('input',e=>audio.currentTime=+e.target.value);$('[data-loop-opening]').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');if(e.currentTarget.classList.contains('active')){audio.currentTime=5.8;audio.play()}});$('[data-pulse-view]').addEventListener('click',e=>{state.pulseView=!state.pulseView;e.currentTarget.classList.toggle('active',state.pulseView);document.querySelectorAll('[data-ring-step]').forEach((el,i)=>el.classList.toggle('on',state.pulseView&&riff[i]))});
  $('[data-play-call]').addEventListener('click',()=>play(seq(rounds[state.round].start,rounds[state.round].call)));$('[data-clear]').addEventListener('click',()=>{state.response=[0,0,0,0,0];renderResponse()});$('[data-transmit]').addEventListener('click',transmit);$('[data-begin]').addEventListener('click',begin);$('[data-restart]').addEventListener('click',()=>{reset();intro.showModal()});$('[data-replay]').addEventListener('click',()=>{success.close();reset();intro.showModal()});
  reset();intro.showModal();
})();
