baseURL = 'https://nickdnickd.com/'
languageCode = 'en-us'
title = 'Nick D Blog'
theme = 'HugoTeX'

[Params]
  darkmode = true # set true if you prefer dark mode

[module]
[[module.imports]]
  path = 'github.com/kaisugi/HugoTeX'