baseURL = 'https://nickdnickd.com/'
languageCode = 'en-us'
title = 'Nick D Blog'
theme = 'HugoTex'

[Params]
  darkmode = true # set true if you prefer dark mode

[author]
  name = "Nick D"
  abstract = "I'm a software engineer and proud new puppy owner."

[module]
[[module.imports]]
  path = 'https://github.com/kaisugi/HugoTeX'